# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 21:24
from __future__ import unicode_literals

import Apps.torneos.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torneo',
            name='user',
            field=models.ForeignKey(on_delete=models.SET(Apps.torneos.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
    ]
